Validate zipfiles
catalyst-cooperative/pudl-archiver pull request #177
Opened 2023-10-02 19:15 UTC by zschira

This PR adds some infrastructure to validate the contents of zipfiles. It allows datasets to specify an expected layout of a zip file, and it will verify that the files exist and that they are valid based on their extension type. This PR also implements this new feature for FERC taxonomies, but all other resources still require implementations to use the validation.

As more validations are added, I think there are potential improvements to this interface, but I felt it would be best to keep it minimal until we better understand how we want to use it. Some improvements I can see include: allow specifying layout using patterns instead of identifying every individual file, validate files without requiring a layout.

2023-11-27 18:02 UTC, jdangerx requested changes
This seems to work and was a nicely self-contained change, which speaks to the design of the validation system! However, there's some extra code organization stuff you can do to make the code easier to reason about and less error-prone in the future, we should address that before merging.

2023-11-27 22:43 UTC, zschira commented
@jdangerx I definitely agree that the previous version had some pretty janky logic. I ended going a slightly different direction to fix it though, and I just used the `ValidationTestResult` class for every individual check instead of accumulating a bunch of checks into a couple different tests. This simplifies the logic quite a bit, but it would mean that the `RunSummary` would be kinda cluttered with the results of all of those tests, so I also added the flag `keep_when_success` to each validation test, so for tests where this is false the summary will not include successful results, so the user doesn't have to comb through hundreds of checks telling them each individual file is not empty.

Let me know if this approach seems reasonable to you.

2023-11-28 15:32 UTC, zschira commented on src/pudl_archiver/frictionless.py
> +        from pudl_archiver.archivers.validate import _validate_file_type
This was to avoid an annoying circular import. There might be some code reorganization to avoid this, but I took the easy way

2023-11-28 15:35 UTC, zschira commented on src/pudl_archiver/archivers/validate.py
> +        return _validate_zip(buffer)
Yeah that's fair. I went ahead and inlined it

2023-11-28 16:02 UTC, jdangerx requested changes
I think it's good to move from this:

> We run **file checks** (`FileValidation`) and **datapackage checks** (`ValidationTestResult`), then collect the file checks into a datapackage check, then collect the **datapackage check outputs** into a **run summary**

To this:

> We run **checks** in a bunch of places and collect their **outputs** in a **run summary**.

That feels like a more useful abstraction to me!

However, when we translate that into the class hierarchy, it seems like we've sort of bundled the tests themselves and the outputs into one class, and it's a little confusing how they all interact. 

It makes sense to me to have `ValidationTestResults` be the **outputs** above, just a class that knows how and if to get serialized in a run summary.

In concrete terms, I think we should pull the validation class methods out of `ValidationTestResults` and into top level functions, make `ValidationTestResults` have a serialize-for-summary method, and return subtypes of ValidationTestResults from the validations so we don't have all sorts of `resource_name: Path | None` and `notes: list[str] | None` clogging up our state space.

I *think* it still makes sense to have separate flags on `ValidationTestResults` for "failing this doesn't fail the whole run" and "we should still report the output, even on success" and have that control the actual behavior of `RunSummary` - though "ignore_failure" and "keep_on_success" are a bit confusing of names. "required_for_run_success" and "always_serialize_output" might be clearer?

2023-11-28 17:55 UTC, jdangerx commented on src/pudl_archiver/frictionless.py
> +        from pudl_archiver.archivers.validate import _validate_file_type
Ahh ok. Works for me.

2023-11-28 23:18 UTC, zschira commented on src/pudl_archiver/archivers/validate.py
> +    keep_when_success: bool = True
Yeah failed, but not required, tests will still end up in the summary, which I think is probably better than just not saying anything when a test fails.

2023-11-29 15:39 UTC, jdangerx approved these changes

2023-11-29 15:54 UTC, merged