fix: removed --dry-run
catalyst-cooperative/pudl-archiver pull request #229
Opened 2023-12-13 16:01 UTC by siwamsingh

this pull request fixes issue #208 
removed "--dry-run" from cli.py and documentation

2023-12-13 16:04 UTC, siwamsingh commented
@jdangerx  i made this pull request but its stuck  😅
 Its my second time contributing can you please check what happened .

2023-12-13 18:49 UTC, jdangerx requested changes
Thanks for the PR! There's still some work left to do since you have to chase down all the downstream references to `dry_run`.

2023-12-13 18:49 UTC, jdangerx commented on src/pudl_archiver/cli.py
While this is where the `--dry-run` argument is passed in, we still need to update all the downstream references - see how `main()` calls 
```python
    asyncio.run(archive_datasets(**vars(args)))
```

And then `archive_datasets` takes a `dry_run` parameter?

2023-12-14 04:14 UTC, closed without merging

2023-12-15 13:39 UTC, jdangerx commented
Hi @siwamsingh !  You closed this - did you still want to try to merge this in?

2023-12-15 16:04 UTC, siwamsingh commented
Sorry @jdangerx  i am not able to work due to some personal problem  😥 . plz assign this issue to someone else i am really sorry.