Fix slack GitHub action
catalyst-cooperative/pudl-archiver pull request #482
Opened 2024-11-19 18:26 UTC by zaneselvans

# Overview

Update our usage of `slack-github-action` to be compatible with the new v2.0 of that action.

# Testing

The same action failed in the main PUDL repo and this fix worked there. Just updating the syntax here. Have not actually tested (but the old way would definitely fail).

2024-11-20 14:22 UTC, e-belfer requested changes
Running the `early_final_release_checker` action [returned something](https://catalystcooperative.slack.com/archives/C03FHB9N0PQ/p1732112369041809) that's clearly not formatted correctly.

> {"attachments":[{"blocks":[{"type":"header","text":{"type":"plain_text","text":"Archiver Run Outcomes"}},{"type":"section","text":{"type":"mrkdwn","text":"Unchanged"}},{"type":"section","text":{"type":"mrkdwn","text":"[eia860](https://zenodo.org/deposit/14192827)\nNo changes."}},{"type":"section","text":{"type":"mrkdwn","text":"[eia861](https://zenodo.org/deposit/14192826)\nNo changes."}},{"type":"section","text":{"type":"mrkdwn","text":"[eia923](https://zenodo.org/deposit/14192828)\nNo changes."}}]}]}

2024-11-20 17:00 UTC, zaneselvans commented
Okay I think this is working correctly now.  I switched to using the `blocks` input to the [`chat.postMessage()` method](https://api.slack.com/methods/chat.postMessage) and modified the script to generate an array of blocks.

2024-11-20 17:02 UTC, zaneselvans commented on scripts/make_slack_notification_message.py
> +            + unchanged_blocks,
An array of blocks, as required for the `blocks` input to the [`chat.postMessage()` method](https://api.slack.com/methods/chat.postMessage).

2024-11-25 14:56 UTC, e-belfer approved these changes
Looks like the slackbot worked as expected this time, thanks for fixing it!

2024-11-25 14:58 UTC, merged